# Generated by Django 5.2.5 on 2025-08-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='authors/')),
                ('fathername', models.CharField(max_length=255)),
                ('publishedbooks', models.IntegerField()),
            ],
        ),
    ]
