# Generated by Django 5.2.5 on 2025-08-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
    ]
