# Generated by Django 5.2.5 on 2025-08-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_rename_book_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='rating',
            new_name='publishyear',
        ),
    ]
