# Generated by Django 5.2.5 on 2025-08-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_rename_rating_books_publishyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='books',
            field=models.TextField(blank=True, null=True),
        ),
    ]
