# Generated by Django 5.2.5 on 2025-08-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_books_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='books',
        ),
    ]
