# Generated by Django 5.2.4 on 2025-08-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='message',
            new_name='details',
        ),
    ]
